### ISSUE TITLE
Hodněkrát "typicky"

### ISSUE THREAD

**Issue by malinajan** [horacekj/bcthesis#2]

**Comment by Bender250** [comment]
*Dal jsem nahodnemu cteni asi 5 minut.*

Hodne casto slovo "uvazit" (alespon tady: https://github.com/horacekj/bcthesis/blob/master/merici-vuz.tex). Rozhodovat, promyslet, zvazovat...

A odkud se inspirujes tim onikanim? Ja jsem zastance autorskeho pluralu (my jsme zvazili) s komentarem v uvodu, ze pro text je pouzit autorsky plural, ale vetsina dila byla tvorena mnou samostatne (viz moje nebo Martina U. diplomka).

**Comment by malinajan** [comment]
Díky za komentář!

Přemýšlel jsem jak to psát a chtěl jsem si zkusit, jak moc mi ona 3. osoba pomůže k větší objektivnosti. Autorský plurál mi přijde takový divný :/. Často nahrazuji tu třetí osobu za zvratné *se*, takže tam tohto snad není nepřiměřeně mnoho.

**Comment by Bender250** [comment]
Chapu.

K tomu *se* (trpny rod) pozor, aby bylo jasne, co jsi delal. Ja v bakalarce pouzival neustale trpny rod a pak jsem to schytal za to, ze neni jasne, co je me autorstvi, protoze vsechno *se stalo tak nejak samo*. Takze trpny rod nekdy ano, ale ne celou praci.
